---
#
# This playbook sets up a new project and utilises OpenShift NetworkPolicy,
# and isolates the project network from other prjects' networks. It also 
# sets project admin role to given user.
#
#
# parameters:
# * user
# * api_url
# * api_key
# * project_name
# * project_description
# * project_display_name
# - project_admin
# * state present/absent
#
# e.g. K8S_AUTH_VERIFY_SSL=no ansible-playbook ocp-project.yml \
#        -i "localhost ansible_connection=local" \
#        -c local
#        -e api_url=https://api.ocp.fi -e user=kube-admin \
#        -e api_key=SMj1HWD9bJrEnvTR0JLR-EMGeeb_eDsaMnB-92-skno \
#        -e project_name=ikke -e project_description="ikkes test" \
#        -e project_display_name=ikke -e project_admin=itengval@redhat.com \
#        -e project_admin -e state=present

- name: Ensure project in OCP, including default policies.
  hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Create a project
      k8s:
        state: "{{ state }}"
        host: "{{ api_url }}"
        username: "{{ user }}"
        api_key: "{{ api_key }}"
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            annotations:
              openshift.io/description: "{{ project_description }}"
              openshift.io/display-name: "{{ project_display_name }}"
            name: "{{ project_name }}"

    - name: Deny all traffic from outside by default
      k8s:
        state: "{{ state }}"
        host: "{{ api_url }}"
        username: "{{ user }}"
        api_key: "{{ api_key }}"
        definition:
          apiVersion: v1
          kind: NetworkPolicy
          apiVersion: v1
          metadata:
            name: allow-from-same-namespace
            namespace: "{{ project_name }}"
          spec:
            podSelector:
            ingress:
            - from:
              - podSelector: {}

    - name: Apply network policy openingns from operations tools
      k8s:
        state: "{{ state }}"
        host: "{{ api_url }}"
        username: "{{ user }}"
        api_key: "{{ api_key }}"
        definition:
          apiVersion: v1
          kind: NetworkPolicy
          metadata:
            name: allow-from-system-projects
            namespace: "{{ project_name }}"
          spec:
            podSelector:
            ingress:
            - from:
              - namespaceSelector:
                  matchLabels:
                    project: default
              - namespaceSelector:
                  matchLabels:
                    project: openshift-infra
              # - namespaceSelector:
              #     matchLabels:
              #       project: logging

    - name: Bind given user to project admin role
      k8s:
        state: "{{ state }}"
        host: "{{ api_url }}"
        username: "{{ user }}"
        api_key: "{{ api_key }}"
        definition:
          kind: RoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: admin
            namespace: "{{ project_name }}"
          subjects:
            - kind: User
              apiGroup: rbac.authorization.k8s.io
              name: "{{ project_admin }}"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: admin