---

roles:
  - src: https://github.com/ikke-t/podman-container-systemd.git
    version: master
    name: podman_container_systemd

collections:
  - name: containers.podman
    source: https://galaxy.ansible.com
