---

- name: ensure Mosquitto MQTT broker container is running
  hosts: all
  vars:
    container_state: running
    container_name: mosquitto
    container_image: 'eclipse-mosquitto:latest'
    container_dir_config: mosquitto-config
    container_dir_data: mosquitto-data
    container_dir_log: mosquitto-log
    container_dir_owner: '1883'
    container_dir_group: root
    container_run_args: >-
      --rm
      -p "9001:9001"
      -p "1883:1883"
      -v "{{exported_container_volumes_basedir}}/{{ container_dir_config }}/mosquitto.conf:/mosquitto/config/mosquitto.conf:Z"
      -v "{{exported_container_volumes_basedir}}/{{ container_dir_data }}:/mosquitto/data:Z"
      -v "{{exported_container_volumes_basedir}}/{{ container_dir_log }}:/mosquitto/log:Z"
    container_firewall_ports:
      #- 8080/tcp

  tasks:

  - name: ensure container files mount point on host
    tags: mount
    file:
      path: "{{exported_container_volumes_basedir}}/{{ item }}"
      owner: "{{ container_dir_owner }}"
      group: "{{ container_dir_group }}"
      state: directory
      recurse: yes
    with_items:
      - "{{ container_dir_config }}"
      - "{{ container_dir_data }}"
      - "{{ container_dir_log }}"

  - name: check if mosquitto.conf exists
    stat:
      path: "{{exported_container_volumes_basedir}}/{{ container_dir_config }}/mosquitto.conf"
    register: mosquitto_conf

  - name: ensure we have config for mqtt
    get_url:
      url: https://raw.githubusercontent.com/eclipse/mosquitto/master/mosquitto.conf
      dest: "{{exported_container_volumes_basedir}}/{{ container_dir_config }}/mosquitto.conf"
      owner: "{{ container_dir_owner }}"
      group: "{{ container_dir_group }}"
      mode: '0644'
    when: mosquitto_conf.stat.exists == False and container_state == 'running'

  - name: ensure container state
    tags: container
    import_role:
      name: podman_container_systemd
