---
- name: basic initialization playbook for rhel host 
  hosts: all
  tasks:

    - name: subscribe to Red Hat
      redhat_subscription:
        state: present
        username: "{{ rhn_user }}"
        password: "{{ rhn_pass }}"
        pool: '^Employee SKU$'
      when: skip_subs is not defined

    - include_role:
        name: common-packages

    - name: register to insights
      command: insights-client --register

    - include_role:
        name: aws_config

    - include_role:
        name: ddns

    - include_role:
        name: cockpit

