---
- name: basic initialization playbook for rhel host 
  hosts: all
  tasks:

    - name: subscribe to Red Hat
      redhat_subscription:
        state: present
        username: "{{ rhn_user }}"
        password: "{{ rhn_pass }}"
        pool: '^Employee SKU$'
      when: skip_subs is not defined

    - include_role:
        name: common-packages

    - name: register to insights
      command: insights-client --register

    - include_role:
        name: aws_config

    - include_role:
        name: ddns

    - include_role:
        name: cockpit

    - name: create admin user
      tags: users
      user:
        name: redhatter
        comment: Admin for the box
        groups: wheel
        password: "{{ rhel_box_admin_pw }}"

    - name: set ssh access for admin user
      tags: users
      authorized_key:
        user: redhatter
        state: present
        key: "{{ tower_pub_key }}"

    - name: allow redhatter to sudo without password (for ansible)
      tags: users
      lineinfile:
        state: present
        path: /etc/sudoers
        line: '%wheel	ALL=(ALL)	NOPASSWD: ALL'
        regexp: '^%wheel ALL'

    - name: make sure root has no password
      tags: users
      user:
        name: root
        password: ''

    - name: enable and run required services
      tags: services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - io.podman.socket
