---

exported_container_volumes_basedir: /var/lib/containers/exported_volumes
my_domain: konttikoulu.fi
tower_pub_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDgzXP3hL7/qdXVVttvHjPvGlZkIHrGdlZrBBIlZcxqTk9Dg0W9nl+pFYAOL3SpUIxa2O0eopK1fMuqPUswUlM982BLchWVIyqSBrMyPtaVXxqXNk0d2wf8l29LbYrN163mR0JtCboWxzSjCwaT74FrgN+ZVBkwr17lRezJ3GNZbFMmVJ6RCcvsEo9+5uVqqJQL0Evs+E2hyA5GOLAkGr/WP5oidVcds7H++AqKYZgX6niqEZQQsD63EfXss6/j2JKl0f8aVnTyFmFlmsP8ZyYaM7332dHna9Dl0McE7CI9nzT6IhjfIFxeIA8FD8rBtVxavjpUM9UIdvwys93UUYXMwP2+cYIbAySAmaosQLldnut3rWXBefBYUetvgxr+036L/DxHkJQ3/9S0ziS10WuZ/pgn/5BMWt3JTQO0KitrZY8BPPVvvqH9nUwNhiyi9BcBjfZrsNWPr7SyuMIydgo2qmDz0bLlpxAc+fAsuPcEC2O3QQPHjFhHKWxLHakSckU= iot-hack
